const store={tasks:JSON.parse(localStorage.getItem("planly_tasks")||"[]"),exams:JSON.parse(localStorage.getItem("planly_exams")||"[]"),grades:JSON.parse(localStorage.getItem("planly_grades")||"[]")};
const save=()=>{localStorage.setItem("planly_tasks",JSON.stringify(store.tasks));localStorage.setItem("planly_exams",JSON.stringify(store.exams));localStorage.setItem("planly_grades",JSON.stringify(store.grades));};
const todayISO=()=>new Date().toISOString().split("T")[0]; const uid=()=>Math.random().toString(36).slice(2);
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab,.view").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.tab).classList.add("active")});
document.getElementById("themeBtn").onclick=()=>document.body.classList.toggle("dark");
function addTask(title,category="Privat",priority="mittel",date=todayISO()){if(!title.trim())return;store.tasks.push({id:uid(),title,category,priority,date,done:false});save();render();}
document.getElementById("addTaskBtn").onclick=()=>{addTask(taskTitle.value,taskCategory.value,taskPriority.value,taskDate.value||todayISO());taskTitle.value=""};
document.getElementById("quickAddBtn").onclick=()=>{let text=quickInput.value.trim();if(!text)return;let p=parseSmart(text);if(p.type==="exam"){store.exams.push({id:uid(),subject:p.subject,topic:p.topic,date:p.date,priority:p.priority});save();render()}else addTask(p.title,p.category,p.priority,p.date);quickInput.value=""};
function parseSmart(text){let lower=text.toLowerCase(),isExam=/klausur|test|arbeit/.test(lower),isSchool=/mathe|deutsch|englisch|bio|geschichte|powi|physik|chemie|spanisch|polnisch/.test(lower),date=todayISO();let d=text.match(/(\d{1,2})\.(\d{1,2})\.?/);if(d){date=`${new Date().getFullYear()}-${String(d[2]).padStart(2,"0")}-${String(d[1]).padStart(2,"0")}`}else if(lower.includes("morgen")){let x=new Date();x.setDate(x.getDate()+1);date=x.toISOString().split("T")[0]}let sm=text.match(/(Mathe|Deutsch|Englisch|Bio|Geschichte|PoWi|Physik|Chemie|Spanisch|Polnisch)/i);return{type:isExam?"exam":"task",title:text,category:isSchool?"Schule":"Privat",priority:isExam?"hoch":"mittel",subject:sm?sm[0]:"Schule",topic:text,date}};
document.getElementById("addExamBtn").onclick=()=>{store.exams.push({id:uid(),subject:examSubject.value||"Fach",topic:examTopic.value||"Thema",date:examDate.value||todayISO(),priority:examPriority.value});save();render()};
document.getElementById("addGradeBtn").onclick=()=>{let points=Number(gradePoints.value),weight=Number(gradeWeight.value||100);if(points<0||points>15)return alert("Punkte 0-15 eintragen.");store.grades.push({id:uid(),subject:gradeSubject.value||"Fach",points,weight});save();render()};
function toggleTask(id){let t=store.tasks.find(x=>x.id===id);t.done=!t.done;save();render()} function del(type,id){store[type]=store[type].filter(x=>x.id!==id);save();render()}
function render(){taskList.innerHTML=store.tasks.map(t=>`<li><span class="${t.done?"done":""}" onclick="toggleTask('${t.id}')">${t.title}<br><small>${t.category} · ${t.date}</small></span><span><span class="badge">${t.priority}</span> <button onclick="del('tasks','${t.id}')">×</button></span></li>`).join("")||"<li>Noch keine Aufgaben.</li>";let today=store.tasks.filter(t=>t.date===todayISO()&&!t.done);todayList.innerHTML=today.map(t=>`<li>${t.title}<span class="badge">${t.priority}</span></li>`).join("")||"<li>Heute ist frei.</li>";weekList.innerHTML=store.tasks.slice(0,5).map(t=>`<li>${t.title}<span class="badge">${t.date}</span></li>`).join("")||"<li>Noch nichts geplant.</li>";let hrs=["08:00","10:00","12:00","14:00","16:00","18:00","20:00"];dayPlan.innerHTML=hrs.map(h=>`<div class="slot"><b>${h}</b><br><span class="hint">Zeitblock frei</span></div>`).join("");weekPlan.innerHTML=["Mo","Di","Mi","Do","Fr","Sa","So"].map(d=>`<div class="day"><b>${d}</b><br><span class="hint">Planen</span></div>`).join("");examList.innerHTML=store.exams.map(e=>{let diff=Math.ceil((new Date(e.date)-new Date(todayISO()))/86400000);return`<li><span><b>${e.subject}</b><br><small>${e.topic}</small></span><span class="badge">${diff} Tage</span></li>`}).join("")||"<li>Noch keine Klausuren.</li>";let by={};store.grades.forEach(g=>(by[g.subject]??=[]).push(g));gradeSummary.innerHTML=Object.entries(by).map(([s,a])=>{let tw=a.reduce((x,g)=>x+g.weight,0),avg=a.reduce((x,g)=>x+g.points*g.weight,0)/tw;return`<div class="slot"><b>${s}</b><br>Ø ${avg.toFixed(1)} Punkte · ${a.length} Noten</div>`}).join("")||"<p class='hint'>Noch keine Noten.</p>";let total=store.tasks.length,done=store.tasks.filter(t=>t.done).length,p=total?Math.round(done/total*100):0;document.querySelector(".circle").style.setProperty("--p",p+"%");progressLabel.textContent=p+"%";focusText.textContent=total?`${done}/${total} Aufgaben erledigt`:"Was ist heute wichtig?";}
render();
